# Generated by Django 4.0.5 on 2022-06-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0002_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'ESTAGIÁRIO'), ('AS', 'ASSISTENTE'), ('JR', 'JUNIOR'), ('PL', 'PLENO'), ('SR', 'SÊNIOR'), ('GR', 'GERENTE'), ('SP', 'Super')], max_length=2),
        ),
    ]
