# Generated by Django 4.0.5 on 2022-07-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0004_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'ESTAGIÁRIO'), ('AS', 'ASSISTENTE'), ('JR', 'JUNIOR'), ('PL', 'PLENO'), ('SR', 'SÊNIOR'), ('GR', 'GERENTE'), ('SP', 'Super'), ('SN', 'Suplente')], max_length=2),
        ),
    ]
